apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "trivy.fullname" . }}-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/data/trivy"
