apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "trivy.fullname" . }}-test-connection"
  labels:
    app: {{ include "trivy.fullname" . }}
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['http://{{ include "trivy.fullname" . }}:8080']
  restartPolicy: Never
